HAI 1.2

VISIBLE "Welcome to CATZCULATOR.lol! :3"

BTW Input here

I HAS A NUMBR1
VISIBLE "GIMMEH NUMBR1 PLZ:"
GIMMEH NUMBR1
NUMBR1 IS NOW A NUMBAR

I HAS A OPERATOR
VISIBLE "WUT OPERATOR U WUNT? (+, -, *, /)"
GIMMEH OPERATOR

I HAS A NUMBR2
VISIBLE "GIMMEH NUMBR2 NOW PLZ:"
GIMMEH NUMBR2
NUMBR2 IS NOW A NUMBAR


BTW now calculate, bro this is so cranky tf xD

OPERATOR, WTF?
    OMG "+"
        VISIBLE "RESULT MEOW::" AN SUM OF NUMBR1 AN NUMBR2 
        GTFO
    
    OMG "-"
        VISIBLE "RESULT MEOW::" AN DIFF OF NUMBR1 AN NUMBR2
        GTFO

    OMG "*"
        VISIBLE "RESULT MEOW::" AN PRODUKT OF NUMBR1 AN NUMBR2
        GTFO

    OMG "/"
        BOTH SAEM NUMBR2 AN 0.0
        O RLY?
            YA RLY
                VISIBLE "ERRORMEOW:: DIV BY 0 IS ILLEGAL MEOW GRRRR"
            NO WAI
                VISIBLE "RESULT MEOW::" AN QUOSHUNT OF NUMBR1 AN NUMBR2
        OIC
        GTFO
    OMG "%"
        VISIBLE "RESULT MEOW (WHY U NEED DAT?!)::" AN MOD OF NUMBR1 AN NUMBR2
        GTFO
    OMGWTF
        VISIBLE "ERRORMEOW:: DATZ NOT A OPERATOR! GRRRR"

OIC


BTW road work ahead, meow
KTHXBYE