HAI 1.2

VISIBLE "Welcome to CATZCULATOR.lol! :3"

BTW Input here

I HAS A NUMBR1
VISIBLE "GIMMEH NUMBR1 PLZ:"
GIMMEH NUMBR1
NUMBR1 IS NOW A NUMBR

I HAS A OPERATOR
VISIBLE "WUT OPERATOR U WUNT? (+, -, *, /)"
GIMMEH OPERATOR

I HAS A NUMBR2
VISIBLE "GIMMEH NUMBR2 NOW PLZ:"
GIMMEH NUMBR2
NUMBR2 IS NOW A NUMBR


BTW now calculate, bro this is so cranky tf xD

OPERATOR, WTF?
    OMG "+"
        VISIBLE "RESULT MEOW" NUMBR1 + NUMBR2
        GTFO
    
    OMG "-"
        VISIBLE "RESULT MEOW" NUMBR1 - NUMBR2
        GTFO
    OMG "*"
        VISIBLE "RESULT MEOW" NUMBR1 * NUMBR2
        GTFO
    OMG "/"
        VISIBLE "RESULT MEOW" NUMBR1 / NUMBR2
        GTFO

    OMGWTF
        VISIBLE "ERRORMEOW: DATZ NOT A OPERATOR! >:("

OIC

KTHXBYE