HAI 1.2

VISIBLE "Welcome to CATZCULATOR.lol! :3"

BTW Input here

I HAS A NUMBR1
VISIBLE "GIMMEH NUMBR1 PLZ:"
GIMMEH NUMBR1
NUMBR1 IS NOW A NUMBAR

I HAS A OPERATOR
VISIBLE "WUT OPERATOR U WUNT? (+, -, *, /)"
GIMMEH OPERATOR

I HAS A NUMBR2
VISIBLE "GIMMEH NUMBR2 NOW PLZ:"
GIMMEH NUMBR2
NUMBR2 IS NOW A NUMBAR

I HAS A RESULT


BTW now calculate, bro this is so cranky tf xD

OPERATOR, WTF?
    OMG "+"
        RESULT R SUM OF NUMBR1 AN NUMBR2 
        GTFO
    
    OMG "-"
        RESULT R DIFF OF NUMBR1 AN NUMBR2
        GTFO

    OMG "*"
        RESULT R PRODUKT OF NUMBR1 AN NUMBR2
        GTFO

    OMG "/"
        BOTH SAEM NUMBR2 AN 0.0
        O RLY?
            YA RLY
                VISIBLE "ERRORMEOW:: DIV BY 0 IS ILLEGAL MEOW GRRRR"
            NO WAI
                RESULT R QUOSHUNT OF NUMBR1 AN NUMBR2
        OIC
        GTFO
    OMG "%"
        RESULT R MOD OF NUMBR1 AN NUMBR2
        GTFO
    OMGWTF
        VISIBLE "ERRORMEOW:: DATZ NOT A OPERATOR! GRRRR"

OIC

RESULT, WTF?
    OMG 67.00
        VISIBLE "SIXX SEEEVUUUN HEIAUEGIUH!!! MEOW"
        GTFO
    OMG 420.00
        VISIBLE "BLAZE IT FAGGOT YURRRRR"
        GTFO
    OMGWTF
        VISIBLE "RESULT IZ: " AN RESULT
        GTFO
OIC

BTW road work ahead, meow
KTHXBYE